**Pandas Seres**
A series is one dimensional labeled array capable of holding any data type.The axis labels are collectively called the index

Creating Series
There are multiple ways to create a pandas series

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
my_list=[10,20,30]
ar=np.array([10,30,30])
d={1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(ar)

0    10
1    30
2    30
dtype: int64

In [10]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [12]:
pd.Series(my_list,index=d,name='Marks')

1    10
2    20
3    30
Name: Marks, dtype: int64