**Finding Missing Data**

In [21]:
import numpy as np
import pandas as pd

In [22]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [4, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)

In [23]:
df

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [24]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [25]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [26]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Removeing Missing data**

In [27]:
df.dropna()

     A  B    C    D
0  1.0  4  1.0  1.0

In [28]:
df

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [29]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Filling the missing data**

In [30]:
df.fillna(0)

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [31]:
df                       #kintu main data thik ase so fillna(0,inplace=true) kore dile tokokn actual data teicng hye jbe

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [33]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  4    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

fillna te coloumn wise fillup hoi,drop na te rwo wise drop kore,selection coloumn wise hoi

In [35]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  4  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0